### PR TITLE
Add random computer names

### PR DESCRIPTION
**Pull request by jamesbcook**
Each request will now send a unique computer name.
There are 4 different buckets of names to choose from and each is chosen
randomly and combined randomly on each function call. Once the computer
name is returned the bytes to broadcast are updated.

The Makefile has also been updated to include the new computers.go file.

### CODE REVIEW

**Comment by jamesbcook** [comment]
respounder output

**Comment by ahhh** [comment]
Why not just make an optional flag where the user can set the computer name? Similarly this feature should be a flag, and not the default functionality.

**Comment by codeexpress** [comment]
Gentlemen, thanks for taking the time to send in your pull requests. Both points make sense. We should make this configurable by letting people decide which hostnames to query for. When that flag isn't set, we should fall back to random strings as hostnames.
@jamesbcook Your commit looks good. I'll test it out in a day or two and will probably add a bit more entropy to the names. Current permutations allow for 108 (3 x 3 x 3 x 4) unique names. I'd probably add a random number to it as well just to defend against a possibility that responder is patched to not answer to these specific 108 names. Very unlikely but possible.

@ahhh Thanks for your pull request. Looks solid, please give me a day or test and merge.

**Comment by ahhh** [comment]
@jamesbcook looks good to me 👍

**Comment by codeexpress** [comment]
Merged with following changes. Thanks @jamesbcook @ahhh 
- Removed the restriction for the hostnames to be more than 15 chars. Hostnames can be smaller now (eg. 'comp01')
- Changed 'computername' to a more appropriate network term 'hostname'
- Removed the option to set computer 'names'. Since we already enabled the -hostname option where users can provide arbitrary hostname, users can write a thin wrapper over respounder if they need to use a specific set of hostnames
- Refactored the `rhostname` (`rcomputername`) option to make it simpler. Current implementation computes the SHA1 sum of current time and uses random bytes from it as hostname.

**Pull request merged**
